# Generated by Django 3.2.8 on 2021-10-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='realm_name',
            field=models.CharField(default='Hell', max_length=16, unique=True),
        ),
    ]
